HR_Management/Controllers/CompanyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace HR_Management.Controllers
{
    public class CompanyController : Controller
    {
        public IActionResult EmployeeList()
        {
			ViewData["Message"] = "All company employees page.";

			return View();
        }

        public IActionResult ComplaintsList()
        {
            ViewData["Message"] = "All company complaints.";

            return View();
        }

        public IActionResult TimeOffList()
        {
            ViewData["Message"] = "All company timeoff requests";

            return View();
        }

        public IActionResult ReviewsList()
        {
            ViewData["Message"] = "All company reviews list.";

            return View();
        }

		public IActionResult PositionsList()
		{
			ViewData["Message"] = "All company reviews list.";

			return View();
		}

        public IActionResult Error()
        {
            return View();
        }
    }
}

HR_Management/Controllers/PositionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace HR_Management.Controllers
{
	public class PositionsController : Controller
	{

		public IActionResult PositionsIndex()
		{
			ViewData["Message"] = "Page to view all positions.";

			return View();
		}

		public IActionResult PositionsIndexManager()
		{
			ViewData["Message"] = "Page to view all positions manager view.";

			return View();
		}

		public IActionResult AddPosition()
		{
			ViewData["Message"] = "Page to view add positions.";

			return View();
		}

		public IActionResult EditPosition()
		{
			ViewData["Message"] = "Page to view edit positions.";

			return View();
		}

		public IActionResult TeamPositionRequests()
		{
			ViewData["Message"] = "Page to view edit positions.";

			return View();
		}

		public IActionResult TeamMemberPosition()
		{
			ViewData["Message"] = "Page to edit complaint status.";

			return View();
		}

		public IActionResult TeamPositions()
		{
			ViewData["Message"] = "Page to view edit positions.";

			return View();
		}


		public IActionResult Error()
		{
			return View();
		}
	}
}

HR_Management/Controllers/ReviewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace HR_Management.Controllers
{
	public class ReviewsController : Controller
	{
		public IActionResult ViewReview()
		{
			ViewData["Message"] = "Page to view a review.";

			return View();
		}

		public IActionResult EditReview()
		{
			ViewData["Message"] = "Page to edit a review.";

			return View();
		}

		public IActionResult ReviewsIndex()
		{
			ViewData["Message"] = "Page to view all the reviews.";

			return View();
		}

		public IActionResult ReviewsIndexManager()
		{
			ViewData["Message"] = "Page to view all the reviews.";

			return View();
		}

		public IActionResult TeamReviews()
		{
			ViewData["Message"] = "Page to view all team reviews.";

			return View();
		}

		public IActionResult TeamMemberReviews()
		{
			ViewData["Message"] = "Page to edit complaint status.";

			return View();
		}

		public IActionResult AddReview()
		{
			ViewData["Message"] = "Page to add a review.";

			return View();
		}

		public IActionResult Error()
		{
			return View();
		}
	}
}

HR_Management/Controllers/TeamsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace HR_Management.Controllers
{
	public class TeamsController : Controller
	{
		public IActionResult ViewTeam()
		{
			ViewData["Message"] = "Page to view all team members.";

			return View();
		}

		public IActionResult EditTeamMember()
		{
			ViewData["Message"] = "Page to edit a team member.";

			return View();
		}

		public IActionResult ViewTeamMember()
		{
			ViewData["Message"] = "Page to view one team member.";

			return View();
		}

		public IActionResult ViewTeamManager()
		{
			ViewData["Message"] = "Page to view team manager/hr view.";

			return View();
		}


        public IActionResult AddTeamMember()
        {
            ViewData["Message"] = "Page to add a team members.";

            return View();
        }

		public IActionResult Error()
		{
			return View();
		}
	}
}

HR_Management/Controllers/TimeOffController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace HR_Management.Controllers
{
	public class TimeOffController : Controller
	{
		public IActionResult ViewTimeOff()
		{
			ViewData["Message"] = "Page to view a specific time off.";

			return View();
		}

        public IActionResult EditTimeOff()
		{
			ViewData["Message"] = "Page to edit a time off.";

			return View();
		}

        public IActionResult TimeOffIndex()
		{
			ViewData["Message"] = "Page to view all the time offs.";

			return View();
		}

		public IActionResult TimeOffIndexManager()
		{
			ViewData["Message"] = "Page to view all the time offs.";

			return View();
		}

		public IActionResult OutstandingTimeOff()
		{
			ViewData["Message"] = "Page to view all the time off requests.";

			return View();
		}

		public IActionResult ExceedingTimeOff()
		{
			ViewData["Message"] = "Page to view all the time off requests.";

			return View();
		}

		public IActionResult TeamMemberTimeOff()
		{
			ViewData["Message"] = "Page to edit complaint status.";

			return View();
		}

		public IActionResult AddTimeOff()
		{
			ViewData["Message"] = "Page to add a time off.";

			return View();
		}

		public IActionResult Error()
		{
			return View();
		}
	}
}

HR_Management/Views/Positions/AddPosition.cshtml
@{
    ViewData["Title"] = "Add Position";
}

    <!-- Manager/HR Messages Page --Page where any manager or HR can promote / add a position to a user -->


<div class="body-style">
    <!-- Sidebar/menu -->
    <nav class="w3-sidebar w3-collapse w3-white w3-animate-left" style="z-index:3;width:300px;" id="mySidebar"><br>
      <div class="w3-container w3-row">
        <div class="w3-col s3">
          <img src="~/images/profile.png" class="w3-circle w3-margin-right" style="width:50px">
        </div>
        <div class="w3-col s9 w3-bar">
          <span>Welcome, <strong>Ike</strong></span><br>
          <a asp-area="" asp-controller="Messages" asp-action="MessagesIndexManager" class="w3-bar-item w3-button w3-text-white" style="background-color: #009688;"><i class="fa fa-envelope"></i></a>
          <a asp-area="" asp-controller="AccountDetails" asp-action="AccountOverviewEditView" class="w3-bar-item w3-button w3-text-teal"><i class="fa fa-user"></i></a>
          <a asp-area="" asp-controller="Settings" asp-action="SettingsOverview" class="w3-bar-item w3-button w3-text-teal"><i class="fa fa-cog"></i></a>
        </div>
      </div>
      <hr>
      <div class="w3-container">
        <h5>Dashboard</h5>
      </div>
      <div class="w3-bar-block">
        <a href="#" class="w3-bar-item w3-button w3-padding-16 w3-hide-large w3-dark-grey w3-hover-black" onclick="w3_close()" title="close menu"><i class="fa fa-remove fa-fw"></i>  Close Menu</a>
        <a asp-area="" asp-controller="AccountDetails" asp-action="AccountOverview" class="w3-bar-item w3-button w3-padding"><i class="fa fa-address-card-o fa-fw"></i>  Account Overview</a>
        <a asp-area="" asp-controller="Teams" asp-action="ViewTeamManager" class="w3-bar-item w3-button w3-padding"><i class="fa fa-users fa-fw"></i>  View Team</a>
        <a asp-area="" asp-controller="TimeOff" asp-action="TimeOffIndexManager" class="w3-bar-item w3-button w3-padding"><i class="fa fa-calendar fa-fw"></i>  Time Off</a>
        <a asp-area="" asp-controller="Reviews" asp-action="ReviewsIndexManager" class="w3-bar-item w3-button w3-padding"><i class="fa fa-comment-o fa-fw"></i>  Reviews</a>
        <a asp-area="" asp-controller="Complaints" asp-action="ComplaintsIndexManager" class="w3-bar-item w3-button w3-padding"><i class="fa fa-bullhorn fa-fw"></i>  Complaints</a>
        <a asp-area="" asp-controller="Positions" asp-action="PositionsIndexManager" class="w3-bar-item w3-button w3-padding w3-blue"><i class="fa fa-line-chart fa-fw"></i>  Position Info</a>
          <div id="demoAcc" class="w3-show w3-white">
            <a asp-area="" asp-controller="Positions" asp-action="PositionsIndexManager"  class="w3-bar-item w3-button">Personal Positions</a>
            <a href="#" class="w3-bar-item w3-button w3-grey">Team Positions</a>
          </div>
        <a asp-area="" asp-controller="Company" asp-action="EmployeeList" class="w3-bar-item w3-button w3-padding"><i class="fa fa-building-o fa-fw"></i>  (HR) Company</a>
        <a asp-area="" asp-controller="Rankings" asp-action="DepartmentRankingIndex" class="w3-bar-item w3-button w3-padding"><i class="fa fa-bar-chart fa-fw"></i>  Ranking</a>
        <a asp-area="" asp-controller="Settings" asp-action="SettingsOverview" class="w3-bar-item w3-button w3-padding"><i class="fa fa-cog fa-fw"></i>  Settings</a><br><br>
      </div>
    </nav>

    <!-- Overlay effect when opening sidebar on small screens -->
    <div class="w3-overlay w3-hide-large w3-animate-opacity" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>


    <div class="w3-main" style="margin-left:340px;margin-top:43px;">
        <div class="main-card-container w3-card-2 w3-white w3-margin-bottom">

            <div class="main-overview">
                <div class="row">
                    <div class="col-md-9">
                        <div class="row">
                            <div class="container col-md-12 my-2">
                                <div class="card py-2">
                                    <div class="row py-9">
                                        <div class="col-md-9 px-2">
                                            <br>
                                            <div class="card-block px-3">
                                                <li class="list-group-item my-4 w3-text-teal card-title" style="width: 100rem;"><h3> <i class="fa fa-calendar fa-fw"></i> Request Time Off</h3></li>
                                                <br>
                                                <div class="card-text w3-text-grey">
                                                    <form class="form-horizontal">
                                                        <h4 class="w3-text-grey"> Complete all fields to request time off.</h4>
                                                        <hr />
                                                        <div asp-validation-summary="All" class="text-danger"></div>
                                                        <div class="form-group">
                                                            <label class="col-md-2 control-label"></label>
                                                            <div class="col-md-10">
                                                                <input class="form-control" type="text"  placeholder="Position Title" />
                                                                <span class="text-danger"></span>
                                                            </div>
                                                        </div>
                                                        <div class="form-group">
                                                            <label class="col-md-2 control-label"></label>
                                                            <div class="col-md-10">
                                                                <input class="form-control" type="text" placeholder="Salary" />
                                                                <span class="text-danger"></span>
                                                            </div>
                                                        </div>
                                                        <div class="form-group">
                                                            <div class="col-md-offset-2 col-md-10">
                                                                <button type="submit" class="btn btn-default">Add Position</button>
                                                            </div>
                                                        </div>
                                                    </form>
                                                </div>
                                                <br>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div> 
    </div>
</div>

HR_Management/Views/Positions/TeamMemberPosition.cshtml
@{
    ViewData["Title"] = "Team Member Positions";
}

    <!-- Manager Position Page --Page where any manager can view a specific team member's total positions.-->


<div class="body-style">
    <!-- Sidebar/menu -->
    <nav class="w3-sidebar w3-collapse w3-white w3-animate-left" style="z-index:3;width:300px;" id="mySidebar"><br>
      <div class="w3-container w3-row">
        <div class="w3-col s3">
          <img src="~/images/profile.png" class="w3-circle w3-margin-right" style="width:50px">
        </div>
        <div class="w3-col s9 w3-bar">
          <span>Welcome, <strong>Ike</strong></span><br>
          <a asp-area="" asp-controller="Messages" asp-action="MessagesIndexManager" class="w3-bar-item w3-button w3-text-white" style="background-color: #009688;"><i class="fa fa-envelope"></i></a>
          <a asp-area="" asp-controller="AccountDetails" asp-action="AccountOverviewEditView" class="w3-bar-item w3-button w3-text-teal"><i class="fa fa-user"></i></a>
          <a asp-area="" asp-controller="Settings" asp-action="SettingsOverview" class="w3-bar-item w3-button w3-text-teal"><i class="fa fa-cog"></i></a>
        </div>
      </div>
      <hr>
      <div class="w3-container">
        <h5>Dashboard</h5>
      </div>
      <div class="w3-bar-block">
        <a href="#" class="w3-bar-item w3-button w3-padding-16 w3-hide-large w3-dark-grey w3-hover-black" onclick="w3_close()" title="close menu"><i class="fa fa-remove fa-fw"></i>  Close Menu</a>
        <a asp-area="" asp-controller="AccountDetails" asp-action="AccountOverview" class="w3-bar-item w3-button w3-padding"><i class="fa fa-address-card-o fa-fw"></i>  Account Overview</a>
        <a asp-area="" asp-controller="Teams" asp-action="ViewTeamManager" class="w3-bar-item w3-button w3-padding"><i class="fa fa-users fa-fw"></i>  View Team</a>
        <a asp-area="" asp-controller="TimeOff" asp-action="TimeOffIndexManager" class="w3-bar-item w3-button w3-padding"><i class="fa fa-calendar fa-fw"></i>  Time Off</a>
        <a asp-area="" asp-controller="Reviews" asp-action="ReviewsIndexManager" class="w3-bar-item w3-button w3-padding"><i class="fa fa-comment-o fa-fw"></i>  Reviews</a>
        <a asp-area="" asp-controller="Complaints" asp-action="ComplaintsIndexManager" class="w3-bar-item w3-button w3-padding"><i class="fa fa-bullhorn fa-fw"></i>  Complaints</a>
        <a asp-area="" asp-controller="Positions" asp-action="PositionsIndexManager" class="w3-bar-item w3-button w3-padding w3-blue"><i class="fa fa-line-chart fa-fw"></i>  Position Info</a>
          <div id="demoAcc" class="w3-show w3-white">
            <a asp-area="" asp-controller="Positions" asp-action="PositionsIndexManager"  class="w3-bar-item w3-button">Personal Positions</a>
            <a href="#" class="w3-bar-item w3-button w3-grey">Team Positions</a>
          </div>
        <a asp-area="" asp-controller="Company" asp-action="EmployeeList" class="w3-bar-item w3-button w3-padding"><i class="fa fa-building-o fa-fw"></i>  (HR) Company</a>
        <a asp-area="" asp-controller="Rankings" asp-action="DepartmentRankingIndex" class="w3-bar-item w3-button w3-padding"><i class="fa fa-bar-chart fa-fw"></i>  Ranking</a>
        <a asp-area="" asp-controller="Settings" asp-action="SettingsOverview" class="w3-bar-item w3-button w3-padding"><i class="fa fa-cog fa-fw"></i>  Settings</a><br><br>
      </div>
    </nav>

    <!-- Overlay effect when opening sidebar on small screens -->
    <div class="w3-overlay w3-hide-large w3-animate-opacity" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>


    <div class="w3-main" style="margin-left:340px;margin-top:43px;">
        <div class="main-card-container w3-card-2 w3-white w3-margin-bottom">

            <div class="main-overview">
                <div class="row">
                    <div class="col-md-9">
                        <div class="row">
                            <div class="container col-md-12 my-2">
                                <div class="card py-2">
                                    <div class="row py-9">
                                        <div class="col-md-9 px-2">
                                            <br>
                                            <div class="card-block px-3">
                                                <li class="list-group-item my-4 w3-text-teal card-title" style="width: 100rem;"><h3> <i class="fa fa-envelope"></i>  View Positions: Ike Tocode</h3></li>
                                                <br>
                                                <div class="card-text w3-text-grey">
                                                    <b> <a asp-area="" asp-controller="Positions" asp-action="AddPosition" class="w3-bar-item w3-button w3-padding w3-blue"> Add Position </a></b>
                                                    <br>
                                                </div>
                                                <br>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        <div class="row py-9">
                            <div class="card py-2">
                                <div class="card-block">
                                      <li class="list-group-item active card-title" style="width: 101rem;"><h5>Positions (2)</h5></li>
                                </div>
                                <table class="table table-striped" style="width: 1200px;">
                                    <tr>
                                        <th>Employee</th>
                                        <th>Date</th>
                                        <th>Position Title</th>
                                        <th>Manager</th>
                                        <th>Salary</th>
                                    </tr>  
                                    <tr>
                                        <td>Ike Tocode</td>
                                        <td>January 10, 2016</td>
                                        <td>Senior Software Developer</td>
                                        <td>Gon Retire</td>
                                        <td>$120,000</td>
                                    </tr>
                                    <tr>
                                        <td>Ike Tocode</td>
                                        <td>April 1, 2007</td>
                                        <td>Junior Developer</td>
                                        <td>Felix M. Hedegaard</td>
                                        <td>$60,000</td>
                                    </tr>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div> 
    </div>
</div>

HR_Management/Views/Positions/TeamPositionRequests.cshtml
@{
    ViewData["Title"] = "Position Requests";
}

    <!-- HR Positions Page --Page where any HR can approve or deny the positions requested by managers -->



<div class="body-style">
    <!-- Sidebar/menu -->
    <nav class="w3-sidebar w3-collapse w3-white w3-animate-left" style="z-index:3;width:300px;" id="mySidebar"><br>
      <div class="w3-container w3-row">
        <div class="w3-col s3">
          <img src="~/images/profile.png" class="w3-circle w3-margin-right" style="width:50px">
        </div>
        <div class="w3-col s9 w3-bar">
          <span>Welcome, <strong>Ike</strong></span><br>
          <a asp-area="" asp-controller="Messages" asp-action="MessagesIndexManager" class="w3-bar-item w3-button w3-text-white" style="background-color: #009688;"><i class="fa fa-envelope"></i></a>
          <a asp-area="" asp-controller="AccountDetails" asp-action="AccountOverviewEditView" class="w3-bar-item w3-button w3-text-teal"><i class="fa fa-user"></i></a>
          <a asp-area="" asp-controller="Settings" asp-action="SettingsOverview" class="w3-bar-item w3-button w3-text-teal"><i class="fa fa-cog"></i></a>
        </div>
      </div>
      <hr>
      <div class="w3-container">
        <h5>Dashboard</h5>
      </div>
      <div class="w3-bar-block">
        <a href="#" class="w3-bar-item w3-button w3-padding-16 w3-hide-large w3-dark-grey w3-hover-black" onclick="w3_close()" title="close menu"><i class="fa fa-remove fa-fw"></i>  Close Menu</a>
        <a asp-area="" asp-controller="AccountDetails" asp-action="AccountOverview" class="w3-bar-item w3-button w3-padding"><i class="fa fa-address-card-o fa-fw"></i>  Account Overview</a>
        <a asp-area="" asp-controller="Teams" asp-action="ViewTeamManager" class="w3-bar-item w3-button w3-padding"><i class="fa fa-users fa-fw"></i>  View Team</a>
        <a asp-area="" asp-controller="TimeOff" asp-action="TimeOffIndexManager" class="w3-bar-item w3-button w3-padding"><i class="fa fa-calendar fa-fw"></i>  Time Off</a>
        <a asp-area="" asp-controller="Reviews" asp-action="ReviewsIndexManager" class="w3-bar-item w3-button w3-padding"><i class="fa fa-comment-o fa-fw"></i>  Reviews</a>
        <a asp-area="" asp-controller="Complaints" asp-action="ComplaintsIndexManager" class="w3-bar-item w3-button w3-padding"><i class="fa fa-bullhorn fa-fw"></i>  Complaints</a>
        <a asp-area="" asp-controller="Positions" asp-action="PositionsIndexManager" class="w3-bar-item w3-button w3-padding w3-blue"><i class="fa fa-line-chart fa-fw"></i>  Position Info</a>
          <div id="demoAcc" class="w3-show w3-white">
            <a asp-area="" asp-controller="Positions" asp-action="PositionsIndexManager"  class="w3-bar-item w3-button">Personal Positions</a>
            <a asp-area="" asp-controller="Positions" asp-action="TeamPositions"  class="w3-bar-item w3-button">Team Positions</a>
            <a href="#" class="w3-bar-item w3-button w3-grey"> (HR) Outstanding Position Requests</a>
          </div>
        <a asp-area="" asp-controller="Company" asp-action="EmployeeList" class="w3-bar-item w3-button w3-padding"><i class="fa fa-building-o fa-fw"></i>  (HR) Company</a>
        <a asp-area="" asp-controller="Rankings" asp-action="DepartmentRankingIndex" class="w3-bar-item w3-button w3-padding"><i class="fa fa-bar-chart fa-fw"></i>  Ranking</a>
        <a asp-area="" asp-controller="Settings" asp-action="SettingsOverview" class="w3-bar-item w3-button w3-padding"><i class="fa fa-cog fa-fw"></i>  Settings</a><br><br>
      </div>
    </nav>

    <!-- Overlay effect when opening sidebar on small screens -->
    <div class="w3-overlay w3-hide-large w3-animate-opacity" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>


    <div class="w3-main" style="margin-left:340px;margin-top:43px;">
        <div class="main-card-container w3-card-2 w3-white w3-margin-bottom">

            <div class="main-overview">
                <div class="row">
                    <div class="col-md-9">
                        <div class="row">
                            <div class="container col-md-12 my-2">
                                <div class="card py-2">
                                    <div class="row py-9">
                                        <div class="col-md-9 px-2">
                                            <br>
                                            <div class="card-block px-3">
                                                <li class="list-group-item my-4 w3-text-teal card-title" style="width: 100rem;"><h3> <i class="fa fa-envelope"></i>  View Positions</h3></li>
                                                <br>
                                                <div class="card-text w3-text-grey">
                                                    <b> <a asp-area="" asp-controller="Positions" asp-action="AddPosition" class="w3-bar-item w3-button w3-padding w3-blue"> Add Position </a></b>
                                                    <br>
                                                </div>
                                                <br>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        <div class="row py-9">
                            <div class="card py-2">
                                <div class="card-block">
                                      <li class="list-group-item active card-title" style="width: 101rem;"><h5>Positions (2)</h5></li>
                                </div>
                                <table class="table table-striped" style="width: 1200px;">
                                    <tr>
                                        <th>Employee</th>
                                        <th>Date</th>
                                        <th>Position Title</th>
                                        <th>Manager</th>
                                        <th>Salary</th>
                                        <th>Approve/Deny</th>
                                    </tr>  
                                    <tr>
                                        <td>Ike Tocode</td>
                                        <td>January 10, 2016</td>
                                        <td>Senior Software Developer</td>
                                        <td>Gon Retire</td>
                                        <td>$120,000</td>
                                        <td><center><i class="fa fa-check"></i>  |  <i class="fa fa-times"></i></center></td>
                                    </tr>
                                    <tr>
                                        <td>Ike Tocode</td>
                                        <td>April 1, 2007</td>
                                        <td>Junior Developer</td>
                                        <td>Felix M. Hedegaard</td>
                                        <td>$60,000</td>
                                        <td><center><i class="fa fa-check"></i>  |  <i class="fa fa-times"></i></center></td>
                                    </tr>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div> 
    </div>
</div>