HR_Management/Controllers/CompanyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace HR_Management.Controllers
{
    public class CompanyController : Controller
    {
        public IActionResult EmployeeList()
        {
			ViewData["Message"] = "All company employees page.";

			return View();
        }

        public IActionResult ComplaintsList()
        {
            ViewData["Message"] = "All company complaints.";

            return View();
        }

        public IActionResult TimeOffList()
        {
            ViewData["Message"] = "All company timeoff requests";

            return View();
        }

        public IActionResult ReviewsList()
        {
            ViewData["Message"] = "All company reviews list.";

            return View();
        }

		public IActionResult PositionsList()
		{
			ViewData["Message"] = "All company reviews list.";

			return View();
		}

        public IActionResult Error()
        {
            return View();
        }
    }
}

HR_Management/Controllers/MessagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace HR_Management.Controllers
{
	public class MessagesController : Controller
	{
		public IActionResult ViewMessage()
		{
			ViewData["Message"] = "Page to view all team members.";

			return View();
		}

		public IActionResult MessagesIndex()
		{
			ViewData["Message"] = "Page to view all messages.";

			return View();
		}

		public IActionResult MessagesIndexManager()
		{
			ViewData["Message"] = "Page to view all messages manager view.";

			return View();
		}

		public IActionResult AddMessage()
		{
			ViewData["Message"] = "Page to add a message.";

			return View();
		}

		public IActionResult Error()
		{
			return View();
		}
	}
}

HR_Management/Controllers/ReviewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace HR_Management.Controllers
{
	public class ReviewsController : Controller
	{
		public IActionResult ViewReview()
		{
			ViewData["Message"] = "Page to view a review.";

			return View();
		}

		public IActionResult EditReview()
		{
			ViewData["Message"] = "Page to edit a review.";

			return View();
		}

		public IActionResult ReviewsIndex()
		{
			ViewData["Message"] = "Page to view all the reviews.";

			return View();
		}

		public IActionResult ReviewsIndexManager()
		{
			ViewData["Message"] = "Page to view all the reviews.";

			return View();
		}

		public IActionResult TeamReviews()
		{
			ViewData["Message"] = "Page to view all team reviews.";

			return View();
		}

		public IActionResult TeamMemberReviews()
		{
			ViewData["Message"] = "Page to edit complaint status.";

			return View();
		}

		public IActionResult AddReview()
		{
			ViewData["Message"] = "Page to add a review.";

			return View();
		}

		public IActionResult Error()
		{
			return View();
		}
	}
}

HR_Management/Controllers/TeamsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace HR_Management.Controllers
{
	public class TeamsController : Controller
	{
		public IActionResult ViewTeam()
		{
			ViewData["Message"] = "Page to view all team members.";

			return View();
		}

		public IActionResult EditTeamMember()
		{
			ViewData["Message"] = "Page to edit a team member.";

			return View();
		}

		public IActionResult ViewTeamMember()
		{
			ViewData["Message"] = "Page to view one team member.";

			return View();
		}

		public IActionResult ViewTeamManager()
		{
			ViewData["Message"] = "Page to view team manager/hr view.";

			return View();
		}


        public IActionResult AddTeamMember()
        {
            ViewData["Message"] = "Page to add a team members.";

            return View();
        }

		public IActionResult Error()
		{
			return View();
		}
	}
}

HR_Management/Controllers/TimeOffController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace HR_Management.Controllers
{
	public class TimeOffController : Controller
	{
		public IActionResult ViewTimeOff()
		{
			ViewData["Message"] = "Page to view a specific time off.";

			return View();
		}

        public IActionResult EditTimeOff()
		{
			ViewData["Message"] = "Page to edit a time off.";

			return View();
		}

        public IActionResult TimeOffIndex()
		{
			ViewData["Message"] = "Page to view all the time offs.";

			return View();
		}

		public IActionResult TimeOffIndexManager()
		{
			ViewData["Message"] = "Page to view all the time offs.";

			return View();
		}

		public IActionResult OutstandingTimeOff()
		{
			ViewData["Message"] = "Page to view all the time off requests.";

			return View();
		}

		public IActionResult ExceedingTimeOff()
		{
			ViewData["Message"] = "Page to view all the time off requests.";

			return View();
		}

		public IActionResult TeamMemberTimeOff()
		{
			ViewData["Message"] = "Page to edit complaint status.";

			return View();
		}

		public IActionResult AddTimeOff()
		{
			ViewData["Message"] = "Page to add a time off.";

			return View();
		}

		public IActionResult Error()
		{
			return View();
		}
	}
}

HR_Management/Views/Reviews/AddReview.cshtml
@{
    ViewData["Title"] = "Add Review";
}

    <!-- Manager/HR Add Review Page --Page where any manager or HR can add a review for their team/a user -->


<div class="body-style">
    <!-- Sidebar/menu -->
    <nav class="w3-sidebar w3-collapse w3-white w3-animate-left" style="z-index:3;width:300px;" id="mySidebar"><br>
      <div class="w3-container w3-row">
        <div class="w3-col s3">
          <img src="~/images/profile.png" class="w3-circle w3-margin-right" style="width:50px">
        </div>
        <div class="w3-col s9 w3-bar">
          <span>Welcome, <strong>Ike</strong></span><br>
          <a asp-area="" asp-controller="Messages" asp-action="MessagesIndexManager" class="w3-bar-item w3-button w3-text-white" style="background-color: #009688;"><i class="fa fa-envelope"></i></a>
          <a asp-area="" asp-controller="AccountDetails" asp-action="AccountOverviewEditView" class="w3-bar-item w3-button w3-text-teal"><i class="fa fa-user"></i></a>
          <a asp-area="" asp-controller="Settings" asp-action="SettingsOverview" class="w3-bar-item w3-button w3-text-teal"><i class="fa fa-cog"></i></a>
        </div>
      </div>
      <hr>
      <div class="w3-container">
        <h5>Dashboard</h5>
      </div>
      <div class="w3-bar-block">
        <a href="#" class="w3-bar-item w3-button w3-padding-16 w3-hide-large w3-dark-grey w3-hover-black" onclick="w3_close()" title="close menu"><i class="fa fa-remove fa-fw"></i>  Close Menu</a>
        <a asp-area="" asp-controller="AccountDetails" asp-action="AccountOverview" class="w3-bar-item w3-button w3-padding"><i class="fa fa-address-card-o fa-fw"></i>  Account Overview</a>
        <a asp-area="" asp-controller="Teams" asp-action="ViewTeamManager" class="w3-bar-item w3-button w3-padding"><i class="fa fa-users fa-fw"></i>  View Team</a>
        <a asp-area="" asp-controller="TimeOff" asp-action="TimeOffIndexManager" class="w3-bar-item w3-button w3-padding"><i class="fa fa-calendar fa-fw"></i>  Time Off</a>
        <a asp-area="" asp-controller="Reviews" asp-action="ReviewsIndexManager" class="w3-bar-item w3-button w3-padding w3-blue"><i class="fa fa-comment-o fa-fw"></i>  Reviews</a>
          <div id="demoAcc" class="w3-show w3-white">
            <a asp-area="" asp-controller="Reviews" asp-action="ReviewsIndexManager" class="w3-bar-item w3-button">Personal Reviews</a>
            <a asp-area="" asp-controller="Reviews" asp-action="TeamReviews" class="w3-bar-item w3-button w3-grey">Team Reviews</a>
          </div>
        <a asp-area="" asp-controller="Complaints" asp-action="ComplaintsIndexManager" class="w3-bar-item w3-button w3-padding"><i class="fa fa-bullhorn fa-fw"></i>  Complaints</a>
        <a asp-area="" asp-controller="Positions" asp-action="PositionsIndexManager" class="w3-bar-item w3-button w3-padding"><i class="fa fa-line-chart fa-fw"></i>  Position Info</a>
        <a asp-area="" asp-controller="Company" asp-action="EmployeeList" class="w3-bar-item w3-button w3-padding"><i class="fa fa-building-o fa-fw"></i>  (HR) Company</a>
        <a asp-area="" asp-controller="Rankings" asp-action="DepartmentRankingIndex" class="w3-bar-item w3-button w3-padding"><i class="fa fa-bar-chart fa-fw"></i>  Ranking</a>
        <a asp-area="" asp-controller="Settings" asp-action="SettingsOverview" class="w3-bar-item w3-button w3-padding"><i class="fa fa-cog fa-fw"></i>  Settings</a><br><br>
      </div>
    </nav>

    <!-- Overlay effect when opening sidebar on small screens -->
    <div class="w3-overlay w3-hide-large w3-animate-opacity" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>


    <div class="w3-main" style="margin-left:340px;margin-top:43px;">
        <div class="main-card-container w3-card-2 w3-white w3-margin-bottom">

            <div class="main-overview">
                <div class="row">
                    <div class="col-md-9">
                        <div class="row">
                            <div class="container col-md-12 my-2">
                                <div class="card py-2">
                                    <div class="row py-9">
                                        <div class="col-md-9 px-2">
                                            <br>
                                            <div class="card-block px-3">
                                                <li class="list-group-item my-4 w3-text-teal card-title" style="width: 100rem;"><h3> <i class="fa fa-calendar fa-fw"></i> Add Review</h3></li>
                                                <br>
                                                <div class="card-text w3-text-grey">
                                                    <form class="form-horizontal">
                                                        <h4 class="w3-text-grey"> Complete all fields to leave a review.</h4>
                                                        <hr />
                                                        <div asp-validation-summary="All" class="text-danger"></div>
                                                        <div class="form-group">
                                                            <label class="col-md-2 control-label"></label>
                                                            <div class="col-md-10">
                                                                <input class="form-control" type="text"  placeholder="Name of Recipient"/>
                                                                <span class="text-danger"></span>
                                                            </div>
                                                        </div>
                                                        <div class="form-group">
                                                            <label class="col-md-2 control-label"></label>
                                                            <div class="col-md-10">
                                                                <textarea rows="4" cols="500" class="form-control" placeholder="Enter Review Here"> </textarea>
                                                                <span class="text-danger"></span>
                                                            </div>
                                                        </div>
                                                        <div class="form-group">
                                                            <label class="col-md-2 control-label"></label>
                                                            <div class="col-md-10">
                                                                <input class="form-control" type="text"  placeholder="Numerical Value" value="" />
                                                                <span class="text-danger"></span>
                                                            </div>
                                                        </div>
                                                        <div class="form-group">
                                                            <div class="col-md-offset-2 col-md-10">
                                                                <button type="submit" class="btn btn-default">Submit Changes</button>
                                                            </div>
                                                        </div>
                                                    </form>
                                                </div>
                                                <br>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div> 
    </div>
</div>

HR_Management/Views/Reviews/EditReview.cshtml
@{
    ViewData["Title"] = "Edit Review";
}

    <!-- HR Edit Review Page --Page where any HR can edit a review for a user -->

<div class="body-style">
    <!-- Sidebar/menu -->
    <nav class="w3-sidebar w3-collapse w3-white w3-animate-left" style="z-index:3;width:300px;" id="mySidebar"><br>
      <div class="w3-container w3-row">
        <div class="w3-col s3">
          <img src="~/images/profile.png" class="w3-circle w3-margin-right" style="width:50px">
        </div>
        <div class="w3-col s9 w3-bar">
          <span>Welcome, <strong>Ike</strong></span><br>
          <a asp-area="" asp-controller="Messages" asp-action="MessagesIndexManager" class="w3-bar-item w3-button w3-text-white" style="background-color: #009688;"><i class="fa fa-envelope"></i></a>
          <a asp-area="" asp-controller="AccountDetails" asp-action="AccountOverviewEditView" class="w3-bar-item w3-button w3-text-teal"><i class="fa fa-user"></i></a>
          <a asp-area="" asp-controller="Settings" asp-action="SettingsOverview" class="w3-bar-item w3-button w3-text-teal"><i class="fa fa-cog"></i></a>
        </div>
      </div>
      <hr>
      <div class="w3-container">
        <h5>Dashboard</h5>
      </div>
      <div class="w3-bar-block">
        <a href="#" class="w3-bar-item w3-button w3-padding-16 w3-hide-large w3-dark-grey w3-hover-black" onclick="w3_close()" title="close menu"><i class="fa fa-remove fa-fw"></i>  Close Menu</a>
        <a asp-area="" asp-controller="AccountDetails" asp-action="AccountOverview" class="w3-bar-item w3-button w3-padding"><i class="fa fa-address-card-o fa-fw"></i>  Account Overview</a>
        <a asp-area="" asp-controller="Teams" asp-action="ViewTeamManager" class="w3-bar-item w3-button w3-padding"><i class="fa fa-users fa-fw"></i>  View Team</a>
        <a asp-area="" asp-controller="TimeOff" asp-action="TimeOffIndexManager" class="w3-bar-item w3-button w3-padding"><i class="fa fa-calendar fa-fw"></i>  Time Off</a>
        <a asp-area="" asp-controller="Reviews" asp-action="ReviewsIndexManager" class="w3-bar-item w3-button w3-padding w3-blue"><i class="fa fa-comment-o fa-fw"></i>  Reviews</a>
          <div id="demoAcc" class="w3-show w3-white">
            <a asp-area="" asp-controller="Reviews" asp-action="ReviewsIndexManager" class="w3-bar-item w3-button">Personal Reviews</a>
            <a asp-area="" asp-controller="Reviews" asp-action="TeamReviews" class="w3-bar-item w3-button w3-grey">Team Reviews</a>
          </div>
        <a asp-area="" asp-controller="Complaints" asp-action="ComplaintsIndexManager" class="w3-bar-item w3-button w3-padding"><i class="fa fa-bullhorn fa-fw"></i>  Complaints</a>
        <a asp-area="" asp-controller="Positions" asp-action="PositionsIndexManager" class="w3-bar-item w3-button w3-padding"><i class="fa fa-line-chart fa-fw"></i>  Position Info</a>
        <a asp-area="" asp-controller="Company" asp-action="EmployeeList" class="w3-bar-item w3-button w3-padding"><i class="fa fa-building-o fa-fw"></i>  (HR) Company</a>
        <a asp-area="" asp-controller="Rankings" asp-action="DepartmentRankingIndex" class="w3-bar-item w3-button w3-padding"><i class="fa fa-bar-chart fa-fw"></i>  Ranking</a>
        <a asp-area="" asp-controller="Settings" asp-action="SettingsOverview" class="w3-bar-item w3-button w3-padding"><i class="fa fa-cog fa-fw"></i>  Settings</a><br><br>
      </div>
    </nav>

    <!-- Overlay effect when opening sidebar on small screens -->
    <div class="w3-overlay w3-hide-large w3-animate-opacity" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>


    <div class="w3-main" style="margin-left:340px;margin-top:43px;">
        <div class="main-card-container w3-card-2 w3-white w3-margin-bottom">

            <div class="main-overview">
                <div class="row">
                    <div class="col-md-9">
                        <div class="row">
                            <div class="container col-md-12 my-2">
                                <div class="card py-2">
                                    <div class="row py-9">
                                        <div class="col-md-9 px-2">
                                            <br>
                                            <div class="card-block px-3">
                                                <li class="list-group-item my-4 w3-text-teal card-title" style="width: 100rem;"><h3> <i class="fa fa-calendar fa-fw"></i> Edit Review</h3></li>
                                                <br>
                                                <div class="card-text w3-text-grey">
                                                    <form class="form-horizontal">
                                                        <h4 class="w3-text-grey"> Complete all fields to leave a review.</h4>
                                                        <hr />
                                                        <div asp-validation-summary="All" class="text-danger"></div>
                                                        <div class="form-group">
                                                            <label class="col-md-2 control-label"></label>
                                                            <div class="col-md-10">
                                                                <input class="form-control" type="text"  placeholder="Name of Recipient" value="Ike Tocode"/>
                                                                <span class="text-danger"></span>
                                                            </div>
                                                        </div>
                                                        <div class="form-group">
                                                            <label class="col-md-2 control-label"></label>
                                                            <div class="col-md-10">
                                                                <textarea rows="4" cols="500" class="form-control" placeholder="Enter Review Here"> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. </textarea>
                                                                <span class="text-danger"></span>
                                                            </div>
                                                        </div>
                                                        <div class="form-group">
                                                            <label class="col-md-2 control-label"></label>
                                                            <div class="col-md-10">
                                                                <input class="form-control" type="text"  placeholder="Numerical Value" value="75" />
                                                                <span class="text-danger"></span>
                                                            </div>
                                                        </div>
                                                        <div class="form-group">
                                                            <div class="col-md-offset-2 col-md-10">
                                                                <button type="submit" class="btn btn-default">Submit Changes</button>
                                                            </div>
                                                        </div>
                                                    </form>
                                                </div>
                                                <br>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div> 
    </div>
</div>

HR_Management/Views/Reviews/TeamMemberReviews.cshtml
@{
    ViewData["Title"] = "Team Members Reviews";
}

    <!-- Team Member Review Page --Page where any manager or HR can view a review for a specfic user -->



<div class="body-style">
    <!-- Sidebar/menu -->
    <nav class="w3-sidebar w3-collapse w3-white w3-animate-left" style="z-index:3;width:300px;" id="mySidebar"><br>
      <div class="w3-container w3-row">
        <div class="w3-col s3">
          <img src="~/images/profile.png" class="w3-circle w3-margin-right" style="width:50px">
        </div>
        <div class="w3-col s9 w3-bar">
          <span>Welcome, <strong>Ike</strong></span><br>
          <a asp-area="" asp-controller="Messages" asp-action="MessagesIndexManager" class="w3-bar-item w3-button w3-text-white" style="background-color: #009688;"><i class="fa fa-envelope"></i></a>
          <a asp-area="" asp-controller="AccountDetails" asp-action="AccountOverviewEditView" class="w3-bar-item w3-button w3-text-teal"><i class="fa fa-user"></i></a>
          <a asp-area="" asp-controller="Settings" asp-action="SettingsOverview" class="w3-bar-item w3-button w3-text-teal"><i class="fa fa-cog"></i></a>
        </div>
      </div>
      <hr>
      <div class="w3-container">
        <h5>Dashboard</h5>
      </div>
      <div class="w3-bar-block">
        <a href="#" class="w3-bar-item w3-button w3-padding-16 w3-hide-large w3-dark-grey w3-hover-black" onclick="w3_close()" title="close menu"><i class="fa fa-remove fa-fw"></i>  Close Menu</a>
        <a asp-area="" asp-controller="AccountDetails" asp-action="AccountOverview" class="w3-bar-item w3-button w3-padding"><i class="fa fa-address-card-o fa-fw"></i>  Account Overview</a>
        <a asp-area="" asp-controller="Teams" asp-action="ViewTeamManager" class="w3-bar-item w3-button w3-padding"><i class="fa fa-users fa-fw"></i>  View Team</a>
        <a asp-area="" asp-controller="TimeOff" asp-action="TimeOffIndexManager" class="w3-bar-item w3-button w3-padding"><i class="fa fa-calendar fa-fw"></i>  Time Off</a>
        <a asp-area="" asp-controller="Reviews" asp-action="ReviewsIndexManager" class="w3-bar-item w3-button w3-padding w3-blue"><i class="fa fa-comment-o fa-fw"></i>  Reviews</a>
          <div id="demoAcc" class="w3-show w3-white">
            <a asp-area="" asp-controller="Reviews" asp-action="ReviewsIndexManager" class="w3-bar-item w3-button">Personal Reviews</a>
            <a href="#" class="w3-bar-item w3-button w3-grey">Team Reviews</a>
          </div>
        <a asp-area="" asp-controller="Complaints" asp-action="ComplaintsIndexManager" class="w3-bar-item w3-button w3-padding"><i class="fa fa-bullhorn fa-fw"></i>  Complaints</a>
        <a asp-area="" asp-controller="Positions" asp-action="PositionsIndexManager" class="w3-bar-item w3-button w3-padding"><i class="fa fa-line-chart fa-fw"></i>  Position Info</a>
        <a asp-area="" asp-controller="Company" asp-action="EmployeeList" class="w3-bar-item w3-button w3-padding"><i class="fa fa-building-o fa-fw"></i>  (HR) Company</a>
        <a asp-area="" asp-controller="Rankings" asp-action="DepartmentRankingIndex" class="w3-bar-item w3-button w3-padding"><i class="fa fa-bar-chart fa-fw"></i>  Ranking</a>
        <a asp-area="" asp-controller="Settings" asp-action="SettingsOverview" class="w3-bar-item w3-button w3-padding"><i class="fa fa-cog fa-fw"></i>  Settings</a><br><br>
      </div>
    </nav>

    <!-- Overlay effect when opening sidebar on small screens -->
    <div class="w3-overlay w3-hide-large w3-animate-opacity" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>


    <div class="w3-main" style="margin-left:340px;margin-top:43px;">
        <div class="main-card-container w3-card-2 w3-white w3-margin-bottom">

            <div class="main-overview">
                <div class="row">
                    <div class="col-md-9">
                        <div class="row">
                            <div class="container col-md-12 my-2">
                                <div class="card py-2">
                                    <div class="row py-9">
                                        <div class="col-md-9 px-2">
                                            <br>
                                            <div class="card-block px-3">
                                                <li class="list-group-item my-4 w3-text-teal card-title" style="width: 100rem;"><h3> <i class="fa fa-comment-o fa-fw"></i> View Reviews: Ike Tocode</h3></li>
                                                <br>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        <div class="row py-9">
                            <div class="card py-2">
                                <div class="card-block">
                                    <a asp-area="" asp-controller="Reviews" asp-action="AddReview"> Add Review </a>
                                    <br>
                                    <br>
                                    <li class="list-group-item active card-title" style="width: 101rem;"><h5>All Reviews (4)</h5></li>
                                </div>
                                <table class="table table-striped" style="width: 1200px;">
                                    <tr>
                                        <th>Title</th>
                                        <th>Date</th>
                                        <th>Review To</th>
                                        <th>Numeric Equivalent</th>
                                        <th>Edit/Delete</th>
                                    </tr>                                   
                                    <tr>
                                        <td><a asp-area="" asp-controller="Reviews" asp-action="ViewReview">2017 Review</a></td>
                                        <td>May 15, 2017</td>
                                        <td>Ike Tocode</td>
                                        <td>75%</td>
                                        <th><center><a asp-area="" asp-controller="Reviews" asp-action="EditReview"><i class="fa fa-pencil-square-o"></i></a>  |  <i class="fa fa-trash-o"></i></center></th>
                                    </tr>
                                    <tr>
                                        <td><a asp-area="" asp-controller="Reviews" asp-action="ViewReview">2016 Review</a></td>
                                        <td>May 29, 2016</td>
                                        <td>Ike Tocode</td>
                                        <td>50%</td>
                                        <th><center><a asp-area="" asp-controller="Reviews" asp-action="EditReview"><i class="fa fa-pencil-square-o"></i></a>  |  <i class="fa fa-trash-o"></i></center></th>
                                    </tr>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div> 
    </div>
</div>