HR_Management/Models/HRModels/Complaints.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace HR_Management.Models.HRModels
{
    public class Complaints
    {
        [Required]
        [Key]
        public int ID { get; set; }
        public int reviewID { get; set; }
        public string status { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public int empId { get; set; }
        public string date { get; set; }
    }
}

HR_Management/Controllers/CompanyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace HR_Management.Controllers
{
    public class CompanyController : Controller
    {
        public IActionResult EmployeeList()
        {
			ViewData["Message"] = "All company employees page.";

			return View();
        }

        public IActionResult ComplaintsList()
        {
            ViewData["Message"] = "All company complaints.";

            return View();
        }

        public IActionResult TimeOffList()
        {
            ViewData["Message"] = "All company timeoff requests";

            return View();
        }

        public IActionResult ReviewsList()
        {
            ViewData["Message"] = "All company reviews list.";

            return View();
        }

		public IActionResult PositionsList()
		{
			ViewData["Message"] = "All company reviews list.";

			return View();
		}

        public IActionResult Error()
        {
            return View();
        }
    }
}

HR_Management/Controllers/ComplaintsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace HR_Management.Controllers
{
	public class ComplaintsController : Controller
	{
		public IActionResult ViewComplaint()
		{
			ViewData["Message"] = "Page to view a complaints.";

			return View();
		}

		public IActionResult EditComplaint()
		{
			ViewData["Message"] = "Page to edit a complaints.";

			return View();
		}

		public IActionResult ComplaintsIndex()
		{
			ViewData["Message"] = "Page to view all the complaints.";

			return View();
		}

		public IActionResult ComplaintsIndexManager()
		{
			ViewData["Message"] = "Page to view all the complaints manager view.";

			return View();
		}

		public IActionResult OutstandingComplaints()
		{
			ViewData["Message"] = "Page to view all the team complaints.";

			return View();
		}

		public IActionResult EditComplaintStatus()
		{
			ViewData["Message"] = "Page to edit complaint status.";

			return View();
		}

		public IActionResult TeamMemberComplaints()
		{
			ViewData["Message"] = "Page to edit complaint status.";

			return View();
		}

		public IActionResult AddComplaint()
		{
			ViewData["Message"] = "Page to add a complaints.";

			return View();
		}

		public IActionResult Error()
		{
			return View();
		}
	}
}

HR_Management/Controllers/ReviewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace HR_Management.Controllers
{
	public class ReviewsController : Controller
	{
		public IActionResult ViewReview()
		{
			ViewData["Message"] = "Page to view a review.";

			return View();
		}

		public IActionResult EditReview()
		{
			ViewData["Message"] = "Page to edit a review.";

			return View();
		}

		public IActionResult ReviewsIndex()
		{
			ViewData["Message"] = "Page to view all the reviews.";

			return View();
		}

		public IActionResult ReviewsIndexManager()
		{
			ViewData["Message"] = "Page to view all the reviews.";

			return View();
		}

		public IActionResult TeamReviews()
		{
			ViewData["Message"] = "Page to view all team reviews.";

			return View();
		}

		public IActionResult TeamMemberReviews()
		{
			ViewData["Message"] = "Page to edit complaint status.";

			return View();
		}

		public IActionResult AddReview()
		{
			ViewData["Message"] = "Page to add a review.";

			return View();
		}

		public IActionResult Error()
		{
			return View();
		}
	}
}

HR_Management/Controllers/TeamsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace HR_Management.Controllers
{
	public class TeamsController : Controller
	{
		public IActionResult ViewTeam()
		{
			ViewData["Message"] = "Page to view all team members.";

			return View();
		}

		public IActionResult EditTeamMember()
		{
			ViewData["Message"] = "Page to edit a team member.";

			return View();
		}

		public IActionResult ViewTeamMember()
		{
			ViewData["Message"] = "Page to view one team member.";

			return View();
		}

		public IActionResult ViewTeamManager()
		{
			ViewData["Message"] = "Page to view team manager/hr view.";

			return View();
		}


        public IActionResult AddTeamMember()
        {
            ViewData["Message"] = "Page to add a team members.";

            return View();
        }

		public IActionResult Error()
		{
			return View();
		}
	}
}

HR_Management/Controllers/TimeOffController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace HR_Management.Controllers
{
	public class TimeOffController : Controller
	{
		public IActionResult ViewTimeOff()
		{
			ViewData["Message"] = "Page to view a specific time off.";

			return View();
		}

        public IActionResult EditTimeOff()
		{
			ViewData["Message"] = "Page to edit a time off.";

			return View();
		}

        public IActionResult TimeOffIndex()
		{
			ViewData["Message"] = "Page to view all the time offs.";

			return View();
		}

		public IActionResult TimeOffIndexManager()
		{
			ViewData["Message"] = "Page to view all the time offs.";

			return View();
		}

		public IActionResult OutstandingTimeOff()
		{
			ViewData["Message"] = "Page to view all the time off requests.";

			return View();
		}

		public IActionResult ExceedingTimeOff()
		{
			ViewData["Message"] = "Page to view all the time off requests.";

			return View();
		}

		public IActionResult TeamMemberTimeOff()
		{
			ViewData["Message"] = "Page to edit complaint status.";

			return View();
		}

		public IActionResult AddTimeOff()
		{
			ViewData["Message"] = "Page to add a time off.";

			return View();
		}

		public IActionResult Error()
		{
			return View();
		}
	}
}

HR_Management/Views/Complaints/ComplaintsIndexManager.cshtml
@{
    ViewData["Title"] = "Personal Complaints";
}

    <!-- Manager Complaints Page --Page where any manager can view their personal complaints -->


<div class="body-style">
    <!-- Sidebar/menu -->
    <nav class="w3-sidebar w3-collapse w3-white w3-animate-left" style="z-index:3;width:300px;" id="mySidebar"><br>
      <div class="w3-container w3-row">
        <div class="w3-col s3">
          <img src="~/images/profile.png" class="w3-circle w3-margin-right" style="width:50px">
        </div>
        <div class="w3-col s9 w3-bar">
          <span>Welcome, <strong>Ike</strong></span><br>
          <a asp-area="" asp-controller="Messages" asp-action="MessagesIndexManager" class="w3-bar-item w3-button w3-text-white" style="background-color: #009688;"><i class="fa fa-envelope"></i></a>
          <a asp-area="" asp-controller="AccountDetails" asp-action="AccountOverviewEditView" class="w3-bar-item w3-button w3-text-teal"><i class="fa fa-user"></i></a>
          <a asp-area="" asp-controller="Settings" asp-action="SettingsOverview" class="w3-bar-item w3-button w3-text-teal"><i class="fa fa-cog"></i></a>
        </div>
      </div>
      <hr>
      <div class="w3-container">
        <h5>Dashboard</h5>
      </div>
      <div class="w3-bar-block">
        <a href="#" class="w3-bar-item w3-button w3-padding-16 w3-hide-large w3-dark-grey w3-hover-black" onclick="w3_close()" title="close menu"><i class="fa fa-remove fa-fw"></i>  Close Menu</a>
        <a asp-area="" asp-controller="AccountDetails" asp-action="AccountOverview" class="w3-bar-item w3-button w3-padding"><i class="fa fa-address-card-o fa-fw"></i>  Account Overview</a>
        <a asp-area="" asp-controller="Teams" asp-action="ViewTeamManager" class="w3-bar-item w3-button w3-padding"><i class="fa fa-users fa-fw"></i>  View Team</a>
        <a asp-area="" asp-controller="TimeOff" asp-action="TimeOffIndexManager" class="w3-bar-item w3-button w3-padding"><i class="fa fa-calendar fa-fw"></i>  Time Off</a>
        <a asp-area="" asp-controller="Reviews" asp-action="ReviewsIndexManager" class="w3-bar-item w3-button w3-padding"><i class="fa fa-comment-o fa-fw"></i>  Reviews</a>
        <a asp-area="" asp-controller="Complaints" asp-action="ComplaintsIndexManager" class="w3-bar-item w3-button w3-padding w3-blue"><i class="fa fa-bullhorn fa-fw"></i>  Complaints</a>
          <div id="demoAcc" class="w3-show w3-white">
            <a href="#" class="w3-bar-item w3-button w3-grey">Personal Complaints</a>
            <a asp-area="" asp-controller="Complaints" asp-action="OutstandingComplaints" class="w3-bar-item w3-button">(HR) Outstanding Complaints</a>
          </div>
		<a asp-area="" asp-controller="Positions" asp-action="PositionsIndexManager" class="w3-bar-item w3-button w3-padding"><i class="fa fa-line-chart fa-fw"></i>  Position Info</a>
        <a asp-area="" asp-controller="Company" asp-action="EmployeeList" class="w3-bar-item w3-button w3-padding"><i class="fa fa-building-o fa-fw"></i>  (HR) Company</a>
        <a asp-area="" asp-controller="Rankings" asp-action="DepartmentRankingIndex" class="w3-bar-item w3-button w3-padding"><i class="fa fa-bar-chart fa-fw"></i>  Ranking</a>
        <a asp-area="" asp-controller="Settings" asp-action="SettingsOverview" class="w3-bar-item w3-button w3-padding"><i class="fa fa-cog fa-fw"></i>  Settings</a><br><br>
      </div>
    </nav>

    <!-- Overlay effect when opening sidebar on small screens -->
    <div class="w3-overlay w3-hide-large w3-animate-opacity" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>


    <div class="w3-main" style="margin-left:340px;margin-top:43px;">
        <div class="main-card-container w3-card-2 w3-white w3-margin-bottom">

            <div class="main-overview">
                <div class="row">
                    <div class="col-md-9">
                        <div class="row">
                            <div class="container col-md-12 my-2">
                                <div class="card py-2">
                                    <div class="row py-9">
                                        <div class="col-md-9 px-2">
                                            <br>
                                            <div class="card-block px-3">
                                                <li class="list-group-item my-4 w3-text-teal card-title" style="width: 100rem;"><h3> <i class="fa fa-bullhorn fa-fw"></i> View Complaints</h3></li>
                                                <br>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        <div class="row py-9">
                            <div class="card py-2">
                                <div class="card-block">
                                      <li class="list-group-item active card-title" style="width: 101rem;"><h5>All Complaints (5)</h5></li>
                                </div>
                                  <table class="table table-striped" style="width: 1200px;">
                                    <tr>
                                        <th>Title</th>
                                        <th>Date</th>
                                        <th>Status</th>
                                        <th>Edit/Delete</th>
                                    </tr>                                   
                                    <tr>
                                        <td><a asp-area="" asp-controller="Complaints" asp-action="ViewComplaint">Low Salary</a></td>
                                        <td>September 17, 2017</td>
                                        <td>Pending</td>
                                        <th><center><a asp-area="" asp-controller="Complaints" asp-action="EditComplaint"><i class="fa fa-pencil-square-o"></i></a>  |  <i class="fa fa-trash-o"></i></center></th>
                                    </tr>
                                    <tr>
                                        <td><a asp-area="" asp-controller="Complaints" asp-action="ViewComplaint">Complaint about 2017 Review</a></td>
                                        <td>May 17, 2017</td>
                                        <td>Investigation in Progress</td>
                                        <th><center><a asp-area="" asp-controller="Complaints" asp-action="EditComplaint"><i class="fa fa-pencil-square-o"></i></a>  |  <i class="fa fa-trash-o"></i></center></th>
                                    </tr>
                                    <tr>
                                        <td><a asp-area="" asp-controller="Complaints" asp-action="ViewComplaint">Lazy Manager</a></td>
                                        <td>May 29, 2016</td>
                                        <td>Resolved</td>
                                        <th><center><a asp-area="" asp-controller="Complaints" asp-action="EditComplaint"><i class="fa fa-pencil-square-o"></i></a>  |  <i class="fa fa-trash-o"></i></center></th>
                                    </tr>
                                    <tr>
                                        <td><a asp-area="" asp-controller="Complaints" asp-action="ViewComplaint">Complaint about 2015 Review</a></td>
                                        <td>May 1, 2015</td>
                                        <td>Resolved</td>
                                        <th><center><a asp-area="" asp-controller="Complaints" asp-action="EditComplaint"><i class="fa fa-pencil-square-o"></i></a>  |  <i class="fa fa-trash-o"></i></center></th>
                                    </tr>
                                    <tr>
                                        <td><a asp-area="" asp-controller="Complaints" asp-action="ViewComplaint">2014 Denied Vacation</a></td>
                                        <td>February 15, 2014</td>
                                        <td>Resolved</td>
                                        <th><center><a asp-area="" asp-controller="Complaints" asp-action="EditComplaint"><i class="fa fa-pencil-square-o"></i></a>  |  <i class="fa fa-trash-o"></i></center></th>
                                    </tr>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div> 
    </div>
</div>

HR_Management/Views/Complaints/EditComplaintStatus.cshtml
@{
    ViewData["Title"] = "Edit Complaints Status";
}

    <!-- HR Edit Complaints Status Page --Page where any HR can update the statud of all complaints except their own -->


<div class="body-style">
    <!-- Sidebar/menu -->
    <nav class="w3-sidebar w3-collapse w3-white w3-animate-left" style="z-index:3;width:300px;" id="mySidebar"><br>
      <div class="w3-container w3-row">
        <div class="w3-col s3">
          <img src="~/images/profile.png" class="w3-circle w3-margin-right" style="width:50px">
        </div>
        <div class="w3-col s9 w3-bar">
          <span>Welcome, <strong>Ike</strong></span><br>
          <a asp-area="" asp-controller="Messages" asp-action="MessagesIndexManager" class="w3-bar-item w3-button w3-text-white" style="background-color: #009688;"><i class="fa fa-envelope"></i></a>
          <a asp-area="" asp-controller="AccountDetails" asp-action="AccountOverviewEditView" class="w3-bar-item w3-button w3-text-teal"><i class="fa fa-user"></i></a>
          <a asp-area="" asp-controller="Settings" asp-action="SettingsOverview" class="w3-bar-item w3-button w3-text-teal"><i class="fa fa-cog"></i></a>
        </div>
      </div>
      <hr>
      <div class="w3-container">
        <h5>Dashboard</h5>
      </div>
      <div class="w3-bar-block">
        <a href="#" class="w3-bar-item w3-button w3-padding-16 w3-hide-large w3-dark-grey w3-hover-black" onclick="w3_close()" title="close menu"><i class="fa fa-remove fa-fw"></i>  Close Menu</a>
        <a asp-area="" asp-controller="AccountDetails" asp-action="AccountOverview" class="w3-bar-item w3-button w3-padding"><i class="fa fa-address-card-o fa-fw"></i>  Account Overview</a>
        <a asp-area="" asp-controller="Teams" asp-action="ViewTeamManager" class="w3-bar-item w3-button w3-padding"><i class="fa fa-users fa-fw"></i>  View Team</a>
        <a asp-area="" asp-controller="TimeOff" asp-action="TimeOffIndexManager" class="w3-bar-item w3-button w3-padding"><i class="fa fa-calendar fa-fw"></i>  Time Off</a>
        <a asp-area="" asp-controller="Reviews" asp-action="ReviewsIndexManager" class="w3-bar-item w3-button w3-padding"><i class="fa fa-comment-o fa-fw"></i>  Reviews</a>
        <a asp-area="" asp-controller="Complaints" asp-action="ComplaintsIndexManager" class="w3-bar-item w3-button w3-padding w3-blue"><i class="fa fa-bullhorn fa-fw"></i>  Complaints</a>
          <div id="demoAcc" class="w3-show w3-white">
            <a asp-area="" asp-controller="Complaints" asp-action="ComplaintsIndexManager" class="w3-bar-item w3-button">Personal Complaints</a>
            <a href="#" class="w3-bar-item w3-button w3-grey">(HR) Outstanding Complaints</a>
          </div>
        <a asp-area="" asp-controller="Positions" asp-action="PositionsIndexManager" class="w3-bar-item w3-button w3-padding"><i class="fa fa-line-chart fa-fw"></i>  Position Info</a>
        <a asp-area="" asp-controller="Company" asp-action="EmployeeList" class="w3-bar-item w3-button w3-padding"><i class="fa fa-building-o fa-fw"></i>  (HR) Company</a>
        <a asp-area="" asp-controller="Rankings" asp-action="DepartmentRankingIndex" class="w3-bar-item w3-button w3-padding"><i class="fa fa-bar-chart fa-fw"></i>  Ranking</a>
        <a asp-area="" asp-controller="Settings" asp-action="SettingsOverview" class="w3-bar-item w3-button w3-padding"><i class="fa fa-cog fa-fw"></i>  Settings</a><br><br>
      </div>
    </nav>

    <!-- Overlay effect when opening sidebar on small screens -->
    <div class="w3-overlay w3-hide-large w3-animate-opacity" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>


    <div class="w3-main" style="margin-left:340px;margin-top:43px;">
        <div class="main-card-container w3-card-2 w3-white w3-margin-bottom">

            <div class="main-overview">
                <div class="row">
                    <div class="col-md-9">
                        <div class="row">
                            <div class="container col-md-12 my-2">
                                <div class="card py-2">
                                    <div class="row py-9">
                                        <div class="col-md-9 px-2">
                                            <br>
                                            <div class="card-block px-3">
                                                <li class="list-group-item my-4 w3-text-teal card-title" style="width: 100rem;"><h3> <i class="fa fa-calendar fa-fw"></i> View Complaint: Low Salary</h3></li>
                                                <br>
                                                <div class="card-text w3-text-grey">
                                                    <p class="card-text"><b>Complaint From:</b> Ike Tocode</p>
                                                    <p class="card-text"><b>Date Delivered</b> May 15, 2017</p>
                                                    <form class="form-horizontal">
                                                        <div>
                                                                <select class="form-control">
                                                                  <option value="vacation">Submitted</option>
                                                                  <option value="vacation">Received</option>
                                                                  <option value="sick">Pending</option>
                                                                  <option value="vacation">Investigation In Progress</option>
                                                                  <option value="vacation">Verifying</option>
                                                                  <option value="vacation">Resolved</option>

                                                                </select>
                                                                <span class="text-danger"></span>
                                                        </div>
													</form>
												</div>
                                                <br>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        <div class="row py-9">
                            <div class="card py-2">
                                <div class="card-block">
                                      <li class="list-group-item active card-title" style="width: 101rem;"><h5>Low Salary</h5></li>
                                </div>
                                <br>
                                
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                                <br>
                            </div>   
                        </div>
                    </div>
                </div>
            </div>
        </div> 
    </div>
</div>

HR_Management/Views/Complaints/OutstandingComplaints.cshtml
@{
    ViewData["Title"] = "Outstanding Complaints";
}

    <!-- HR Complaints Page --Page where any HR can view all unresolved complaints -->



<div class="body-style">
    <!-- Sidebar/menu -->
    <nav class="w3-sidebar w3-collapse w3-white w3-animate-left" style="z-index:3;width:300px;" id="mySidebar"><br>
      <div class="w3-container w3-row">
        <div class="w3-col s3">
          <img src="~/images/profile.png" class="w3-circle w3-margin-right" style="width:50px">
        </div>
        <div class="w3-col s9 w3-bar">
          <span>Welcome, <strong>Ike</strong></span><br>
          <a asp-area="" asp-controller="Messages" asp-action="MessagesIndexManager" class="w3-bar-item w3-button w3-text-white" style="background-color: #009688;"><i class="fa fa-envelope"></i></a>
          <a asp-area="" asp-controller="AccountDetails" asp-action="AccountOverviewEditView" class="w3-bar-item w3-button w3-text-teal"><i class="fa fa-user"></i></a>
          <a asp-area="" asp-controller="Settings" asp-action="SettingsOverview" class="w3-bar-item w3-button w3-text-teal"><i class="fa fa-cog"></i></a>
        </div>
      </div>
      <hr>
      <div class="w3-container">
        <h5>Dashboard</h5>
      </div>
      <div class="w3-bar-block">
        <a href="#" class="w3-bar-item w3-button w3-padding-16 w3-hide-large w3-dark-grey w3-hover-black" onclick="w3_close()" title="close menu"><i class="fa fa-remove fa-fw"></i>  Close Menu</a>
        <a asp-area="" asp-controller="AccountDetails" asp-action="AccountOverview" class="w3-bar-item w3-button w3-padding"><i class="fa fa-address-card-o fa-fw"></i>  Account Overview</a>
        <a asp-area="" asp-controller="Teams" asp-action="ViewTeamManager" class="w3-bar-item w3-button w3-padding"><i class="fa fa-users fa-fw"></i>  View Team</a>
        <a asp-area="" asp-controller="TimeOff" asp-action="TimeOffIndexManager" class="w3-bar-item w3-button w3-padding"><i class="fa fa-calendar fa-fw"></i>  Time Off</a>
        <a asp-area="" asp-controller="Reviews" asp-action="ReviewsIndexManager" class="w3-bar-item w3-button w3-padding"><i class="fa fa-comment-o fa-fw"></i>  Reviews</a>
        <a asp-area="" asp-controller="Complaints" asp-action="ComplaintsIndexManager" class="w3-bar-item w3-button w3-padding w3-blue"><i class="fa fa-bullhorn fa-fw"></i>  Complaints</a>
          <div id="demoAcc" class="w3-show w3-white">
            <a asp-area="" asp-controller="Complaints" asp-action="ComplaintsIndexManager" class="w3-bar-item w3-button">Personal Complaints</a>
            <a href="#" class="w3-bar-item w3-button w3-grey">(HR) Outstanding Complaints</a>
          </div>
        <a asp-area="" asp-controller="Positions" asp-action="PositionsIndexManager" class="w3-bar-item w3-button w3-padding"><i class="fa fa-line-chart fa-fw"></i>  Position Info</a>
        <a asp-area="" asp-controller="Company" asp-action="EmployeeList" class="w3-bar-item w3-button w3-padding"><i class="fa fa-building-o fa-fw"></i>  (HR) Company</a>
        <a asp-area="" asp-controller="Rankings" asp-action="DepartmentRankingIndex" class="w3-bar-item w3-button w3-padding"><i class="fa fa-bar-chart fa-fw"></i>  Ranking</a>
        <a asp-area="" asp-controller="Settings" asp-action="SettingsOverview" class="w3-bar-item w3-button w3-padding"><i class="fa fa-cog fa-fw"></i>  Settings</a><br><br>
      </div>
    </nav>

    <!-- Overlay effect when opening sidebar on small screens -->
    <div class="w3-overlay w3-hide-large w3-animate-opacity" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>


    <div class="w3-main" style="margin-left:340px;margin-top:43px;">
        <div class="main-card-container w3-card-2 w3-white w3-margin-bottom">

            <div class="main-overview">
                <div class="row">
                    <div class="col-md-9">
                        <div class="row">
                            <div class="container col-md-12 my-2">
                                <div class="card py-2">
                                    <div class="row py-9">
                                        <div class="col-md-9 px-2">
                                            <br>
                                            <div class="card-block px-3">
                                                <li class="list-group-item my-4 w3-text-teal card-title" style="width: 100rem;"><h3> <i class="fa fa-bullhorn fa-fw"></i> View Complaints</h3></li>
                                                <br>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        <div class="row py-9">
                            <div class="card py-2">
                                <div class="card-block">
                                      <li class="list-group-item active card-title" style="width: 101rem;"><h5>All Complaints (5)</h5></li>
                                </div>
                                  <table class="table table-striped" style="width: 1200px;">
                                    <tr>
                                        <th>Title</th>
                                        <th>Date</th>
                                        <th>Status</th>
                                        <th>Change Status</th>
                                    </tr>                                   
                                    <tr>
                                        <td><a asp-area="" asp-controller="Complaints" asp-action="ViewComplaint">Low Salary</a></td>
                                        <td>September 17, 2017</td>
                                        <td>Pending</td>
                                        <th><center><a asp-area="" asp-controller="Complaints" asp-action="EditComplaintStatus"><i class="fa fa-pencil-square-o"></i></a></i></center></th>
                                    </tr>
                                    <tr>
                                        <td><a asp-area="" asp-controller="Complaints" asp-action="ViewComplaint">Complaint about 2017 Review</a></td>
                                        <td>May 17, 2017</td>
                                        <td>Investigation in Progress</td>
                                        <th><center><a asp-area="" asp-controller="Complaints" asp-action="EditComplaintStatus"><i class="fa fa-pencil-square-o"></i></a></i></center></th>
                                    </tr>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div> 
    </div>
</div>