HR_Management/Controllers/MessagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace HR_Management.Controllers
{
	public class MessagesController : Controller
	{
		public IActionResult ViewMessage()
		{
			ViewData["Message"] = "Page to view all team members.";

			return View();
		}

		public IActionResult MessagesIndex()
		{
			ViewData["Message"] = "Page to view all messages.";

			return View();
		}

		public IActionResult MessagesIndexManager()
		{
			ViewData["Message"] = "Page to view all messages manager view.";

			return View();
		}

		public IActionResult AddMessage()
		{
			ViewData["Message"] = "Page to add a message.";

			return View();
		}

		public IActionResult Error()
		{
			return View();
		}
	}
}

HR_Management/Controllers/ReviewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace HR_Management.Controllers
{
	public class ReviewsController : Controller
	{
		public IActionResult ViewReview()
		{
			ViewData["Message"] = "Page to view a review.";

			return View();
		}

		public IActionResult EditReview()
		{
			ViewData["Message"] = "Page to edit a review.";

			return View();
		}

		public IActionResult ReviewsIndex()
		{
			ViewData["Message"] = "Page to view all the reviews.";

			return View();
		}

		public IActionResult ReviewsIndexManager()
		{
			ViewData["Message"] = "Page to view all the reviews.";

			return View();
		}

		public IActionResult TeamReviews()
		{
			ViewData["Message"] = "Page to view all team reviews.";

			return View();
		}

		public IActionResult TeamMemberReviews()
		{
			ViewData["Message"] = "Page to edit complaint status.";

			return View();
		}

		public IActionResult AddReview()
		{
			ViewData["Message"] = "Page to add a review.";

			return View();
		}

		public IActionResult Error()
		{
			return View();
		}
	}
}

HR_Management/Controllers/SettingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace HR_Management.Controllers
{
	public class SettingsController : Controller
	{
		public IActionResult SettingsOverview()
		{
			ViewData["Message"] = "Your application settings overview page.";

			return View();
		}

		public IActionResult QuitJob()
		{
			ViewData["Message"] = "Quit Job.";

			return View();
		}



		public IActionResult Error()
		{
			return View();
		}
	}
}

HR_Management/Controllers/TeamsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace HR_Management.Controllers
{
	public class TeamsController : Controller
	{
		public IActionResult ViewTeam()
		{
			ViewData["Message"] = "Page to view all team members.";

			return View();
		}

		public IActionResult EditTeamMember()
		{
			ViewData["Message"] = "Page to edit a team member.";

			return View();
		}

		public IActionResult ViewTeamMember()
		{
			ViewData["Message"] = "Page to view one team member.";

			return View();
		}

		public IActionResult ViewTeamManager()
		{
			ViewData["Message"] = "Page to view team manager/hr view.";

			return View();
		}


        public IActionResult AddTeamMember()
        {
            ViewData["Message"] = "Page to add a team members.";

            return View();
        }

		public IActionResult Error()
		{
			return View();
		}
	}
}

HR_Management/Controllers/TimeOffController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace HR_Management.Controllers
{
	public class TimeOffController : Controller
	{
		public IActionResult ViewTimeOff()
		{
			ViewData["Message"] = "Page to view a specific time off.";

			return View();
		}

        public IActionResult EditTimeOff()
		{
			ViewData["Message"] = "Page to edit a time off.";

			return View();
		}

        public IActionResult TimeOffIndex()
		{
			ViewData["Message"] = "Page to view all the time offs.";

			return View();
		}

		public IActionResult TimeOffIndexManager()
		{
			ViewData["Message"] = "Page to view all the time offs.";

			return View();
		}

		public IActionResult OutstandingTimeOff()
		{
			ViewData["Message"] = "Page to view all the time off requests.";

			return View();
		}

		public IActionResult ExceedingTimeOff()
		{
			ViewData["Message"] = "Page to view all the time off requests.";

			return View();
		}

		public IActionResult TeamMemberTimeOff()
		{
			ViewData["Message"] = "Page to edit complaint status.";

			return View();
		}

		public IActionResult AddTimeOff()
		{
			ViewData["Message"] = "Page to add a time off.";

			return View();
		}

		public IActionResult Error()
		{
			return View();
		}
	}
}

HR_Management/Views/Settings/QuitJob.cshtml
@{
    ViewData["Title"] = "Quit Job";
}

    <!-- Quit Job Page --Page where user quits job by inputting their 2 week notice -->


<div class="body-style">
    <!-- Sidebar/menu -->
    <nav class="w3-sidebar w3-collapse w3-white w3-animate-left" style="z-index:3;width:300px;" id="mySidebar"><br>
      <div class="w3-container w3-row">
        <div class="w3-col s3">
          <img src="~/images/profile.png" class="w3-circle w3-margin-right" style="width:50px">
        </div>
        <div class="w3-col s9 w3-bar">
          <span>Welcome, <strong>Ike</strong></span><br>
          <a asp-area="" asp-controller="Messages" asp-action="MessagesIndex" class="w3-bar-item w3-button w3-text-teal"><i class="fa fa-envelope"></i></a>
          <a asp-area="" asp-controller="AccountDetails" asp-action="AccountOverviewEditView" class="w3-bar-item w3-button w3-text-teal"><i class="fa fa-user"></i></a>
          <a asp-area="" asp-controller="Settings" asp-action="SettingsOverview" class="w3-bar-item w3-button w3-text-white" style="background-color: #009688;"><i class="fa fa-cog"></i></a>
        </div>
      </div>
      <hr>
      <div class="w3-container">
        <h5>Dashboard</h5>
      </div>
      <div class="w3-bar-block">
        <a href="#" class="w3-bar-item w3-button w3-padding-16 w3-hide-large w3-dark-grey w3-hover-black" onclick="w3_close()" title="close menu"><i class="fa fa-remove fa-fw"></i>  Close Menu</a>
        <a asp-area="" asp-controller="AccountDetails" asp-action="AccountOverview" class="w3-bar-item w3-button w3-padding"><i class="fa fa-address-card-o fa-fw"></i>  Account Overview</a>
        <a asp-area="" asp-controller="Teams" asp-action="ViewTeam" class="w3-bar-item w3-button w3-padding"><i class="fa fa-users fa-fw"></i>  View Team</a>
        <a asp-area="" asp-controller="TimeOff" asp-action="TimeOffIndex" class="w3-bar-item w3-button w3-padding"><i class="fa fa-calendar fa-fw"></i>  Time Off</a>
        <a asp-area="" asp-controller="Reviews" asp-action="ReviewsIndex" class="w3-bar-item w3-button w3-padding"><i class="fa fa-comment-o fa-fw"></i>  Reviews</a>
        <a asp-area="" asp-controller="Complaints" asp-action="ComplaintsIndex" class="w3-bar-item w3-button w3-padding"><i class="fa fa-bullhorn fa-fw"></i>  Complaints</a>
        <a asp-area="" asp-controller="Positions" asp-action="PositionsIndex" class="w3-bar-item w3-button w3-padding"><i class="fa fa-line-chart fa-fw"></i>  Position Info</a>
        <a asp-area="" asp-controller="Rankings" asp-action="DepartmentRankingIndex" class="w3-bar-item w3-button w3-padding"><i class="fa fa-bar-chart fa-fw"></i>  Ranking</a>
        <a asp-area="" asp-controller="Settings" asp-action="SettingsOverview" class="w3-bar-item w3-button w3-padding w3-blue"><i class="fa fa-cog fa-fw"></i>  Settings</a><br><br>
      </div>
    </nav>

    <!-- Overlay effect when opening sidebar on small screens -->
    <div class="w3-overlay w3-hide-large w3-animate-opacity" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>


    <div class="w3-main" style="margin-left:340px;margin-top:43px;">
        <div class="main-card-container w3-card-2 w3-white w3-margin-bottom">

            <div class="main-overview">
                <div class="row">
                    <div class="col-md-9">
                        <div class="row">
                            <div class="container col-md-12 my-2">
                                <div class="card py-2">
                                    <div class="row py-9">
                                        <div class="col-md-9 px-2">
                                            <br>
                                            <div class="card-block px-3">
                                                <li class="list-group-item my-4 w3-text-teal card-title" style="width: 100rem;"><h3><i class="fa fa-cog fa-fw"></i> Quit Position</h3></li>
                                                <br>
                                            </div>
                                                <form>
                                                    <h4 class="w3-text-grey"> Submit Your Two Week Notice</h4>
                                                    <hr />
                                                    <div asp-validation-summary="All" class="text-danger"></div>
                                                    <div>
                                                        <label class="control-label"></label>
                                                        <div >
                                                            <textarea rows="4" cols="500" class="form-control" placeholder="Enter Review Here"> </textarea>
                                                            <span class="text-danger"></span>
                                                        </div>
                                                    </div>
    												<br>
                                                    <div >
                                                        <div>
                                                            <button type="submit" class="btn btn-default">Quit Job</button>
                                                        </div>
                                                    </div>
                                                </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div> 
    </div>
</div>

HR_Management/Views/Settings/SettingsOverview.cshtml
@{
    ViewData["Title"] = "Settings";
}

    <!-- Settings Page --Page where any user can change their settings -->


<div class="body-style">
    <!-- Sidebar/menu -->
    <nav class="w3-sidebar w3-collapse w3-white w3-animate-left" style="z-index:3;width:300px;" id="mySidebar"><br>
      <div class="w3-container w3-row">
        <div class="w3-col s3">
          <img src="~/images/profile.png" class="w3-circle w3-margin-right" style="width:50px">
        </div>
        <div class="w3-col s9 w3-bar">
          <span>Welcome, <strong>Ike</strong></span><br>
          <a asp-area="" asp-controller="Messages" asp-action="MessagesIndex" class="w3-bar-item w3-button w3-text-teal"><i class="fa fa-envelope"></i></a>
          <a asp-area="" asp-controller="AccountDetails" asp-action="AccountOverviewEditView" class="w3-bar-item w3-button w3-text-teal"><i class="fa fa-user"></i></a>
          <a asp-area="" asp-controller="Settings" asp-action="SettingsOverview" class="w3-bar-item w3-button w3-text-white" style="background-color: #009688;"><i class="fa fa-cog"></i></a>
        </div>
      </div>
      <hr>
      <div class="w3-container">
        <h5>Dashboard</h5>
      </div>
      <div class="w3-bar-block">
        <a href="#" class="w3-bar-item w3-button w3-padding-16 w3-hide-large w3-dark-grey w3-hover-black" onclick="w3_close()" title="close menu"><i class="fa fa-remove fa-fw"></i>  Close Menu</a>
        <a asp-area="" asp-controller="AccountDetails" asp-action="AccountOverview" class="w3-bar-item w3-button w3-padding"><i class="fa fa-address-card-o fa-fw"></i>  Account Overview</a>
        <a asp-area="" asp-controller="Teams" asp-action="ViewTeam" class="w3-bar-item w3-button w3-padding"><i class="fa fa-users fa-fw"></i>  View Team</a>
        <a asp-area="" asp-controller="TimeOff" asp-action="TimeOffIndex" class="w3-bar-item w3-button w3-padding"><i class="fa fa-calendar fa-fw"></i>  Time Off</a>
        <a asp-area="" asp-controller="Reviews" asp-action="ReviewsIndex" class="w3-bar-item w3-button w3-padding"><i class="fa fa-comment-o fa-fw"></i>  Reviews</a>
        <a asp-area="" asp-controller="Complaints" asp-action="ComplaintsIndex" class="w3-bar-item w3-button w3-padding"><i class="fa fa-bullhorn fa-fw"></i>  Complaints</a>
        <a asp-area="" asp-controller="Positions" asp-action="PositionsIndex" class="w3-bar-item w3-button w3-padding"><i class="fa fa-line-chart fa-fw"></i>  Position Info</a>
        <a asp-area="" asp-controller="Rankings" asp-action="DepartmentRankingIndex" class="w3-bar-item w3-button w3-padding"><i class="fa fa-bar-chart fa-fw"></i>  Ranking</a>
        <a asp-area="" asp-controller="Settings" asp-action="SettingsOverview" class="w3-bar-item w3-button w3-padding w3-blue"><i class="fa fa-cog fa-fw"></i>  Settings</a><br><br>
      </div>
    </nav>

    <!-- Overlay effect when opening sidebar on small screens -->
    <div class="w3-overlay w3-hide-large w3-animate-opacity" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>


    <div class="w3-main" style="margin-left:340px;margin-top:43px;">
        <div class="main-card-container w3-card-2 w3-white w3-margin-bottom">

            <div class="main-overview">
                <div class="row">
                    <div class="col-md-9">
                        <div class="row">
                            <div class="container col-md-12 my-2">
                                <div class="card py-2">
                                    <div class="row py-9">
                                        <div class="col-md-9 px-2">
                                            <br>
                                            <div class="card-block px-3">
                                                <li class="list-group-item my-4 w3-text-teal card-title" style="width: 100rem;"><h3><i class="fa fa-cog fa-fw"></i> Settings</h3></li>
                                                <br>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        <div class="row py-9">
                            <div class="card py-2">
                                <div class="card-block">
                                      <li class="list-group-item active card-title" style="width: 101rem;"><h5>Account Settings</h5></li>
                                </div>
                                <ul class="list-group list-group-flush">
                                    <li class="list-group-item"><a asp-area="" asp-controller="Account" asp-action="ResetPassword">Change Password</a></li>
                                    <li class="list-group-item"><a asp-area="" asp-controller="Settings" asp-action="QuitJob">Quit Job</a></li>

                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div> 
    </div>
</div>